# Generated by Django 6.0.1 on 2026-01-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='Company logo (recommended: transparent PNG)', null=True, upload_to='experience/logos/'),
        ),
        migrations.AddField(
            model_name='experience',
            name='work_image',
            field=models.ImageField(blank=True, help_text='Project screenshot or relevant visual', null=True, upload_to='experience/images/'),
        ),
    ]
