# Generated by Django 6.0.1 on 2026-01-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_experience_company_logo_experience_work_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile photo (square recommended)', null=True, upload_to='profile/'),
        ),
    ]
