# Generated by Django 6.0.1 on 2026-01-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='logo',
            field=models.ImageField(blank=True, help_text='Issuer/Certification logo', null=True, upload_to='certifications/logos/'),
        ),
        migrations.AddField(
            model_name='education',
            name='logo',
            field=models.ImageField(blank=True, help_text='Institution logo', null=True, upload_to='education/logos/'),
        ),
    ]
