# Generated by Django 6.0.1 on 2026-01-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_certification_logo_education_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='logo',
            field=models.FileField(blank=True, help_text='Issuer logo (PNG, JPG, or SVG)', null=True, upload_to='certifications/logos/'),
        ),
        migrations.AlterField(
            model_name='education',
            name='logo',
            field=models.FileField(blank=True, help_text='Institution logo (PNG, JPG, or SVG)', null=True, upload_to='education/logos/'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_logo',
            field=models.FileField(blank=True, help_text='Company logo (PNG, JPG, or SVG)', null=True, upload_to='experience/logos/'),
        ),
    ]
