# Generated by Django 6.0.1 on 2026-01-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_certification_logo_alter_education_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='level',
            field=models.CharField(choices=[('PRIMARY', 'Primary School'), ('SECONDARY', 'Secondary School'), ('TERTIARY', 'University/College'), ('POSTGRAD', 'Postgraduate')], default='TERTIARY', max_length=20),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(help_text='Degree name or certificate (e.g., KCPE, KCSE, BSc)', max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.CharField(blank=True, help_text='Grade/Score (e.g., A, B+, First Class)', max_length=100),
        ),
    ]
